# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fe99d7c384849b75ee722851844db9244f774f5303915fa0cf4e195f98e65aa558193e9981bb72952ee6d9ccb66cfd13314d4e8750cd578edf06564a253a4b1

test:
  secret_key_base: bcee384260b50e9d16ea6199f16ff9d92984a12ee1d72be4a09407b2cdd674059c8499c73104914e9b9194e8864f5d62f9fa1321499e8703e5e886309fe5eb63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
